FROM jupyter/scipy-notebook:65761486d5d3
USER root
RUN apt-get update
RUN apt-get install -y python3-dev libpq-dev

RUN pip install --upgrade pip && pip install ipython-sql && pip install psycopg2 && pip install sqlalchemy && pip install joblib

CMD jupyter notebook --allow-root --NotebookApp.port="80" --NotebookApp.token="$NOTEBOOK_PASSWORD" /opt/analysis
